services:
  goodwords:
    build: .
    container_name: goodwords-service
    volumes: 
      - ./service/config/config.toml:/app/service/config/config.toml
      - ./logs/:/app/logs/
      - ./output/:/app/output/
